os:
  - linux
services:
  - docker
sudo: required
dist: trusty
script:
  - docker build --no-cache -t svit-service-tests -f 'test.Dockerfile' .
  - containerId=$(docker create svit-service-tests)
  - docker cp "${containerId}":app.coverage.lcov .
  - docker rm "${containerId}"

after_success:
  - bash <(curl -s https://codecov.io/bash)

