os:
  - linux
  - osx
language: swift
sudo: required
dist: trusty
osx_image: xcode11.3
before_script:
  - apt-get update; apt-get install -y libssl-dev zlib1g-dev sqlite3 libsqlite3-dev
script:
  - swift build
  - swift test

