os:
  - osx
# requires a minimum Swift tools version of 5.1.0 (currently 4.1.0)
# - linux
language: swift
sudo: required
dist: trusty
osx_image: xcode11.3
script:
  - swift build
  - swift test
after_success:
  - bash scripts/export-codecov.sh
  - bash <(curl -s https://codecov.io/bash) -J "app" -D ".build/debug"

