version: '3.1'

services:
  db:
    image: postgres:12-alpine
    container_name: svit-db
    restart: always
    environment:
      POSTGRES_USER: ${SVIT_DB_USER}
      POSTGRES_DB: ${SVIT_DB_NAME}
      POSTGRES_PASSWORD: ${SVIT_DB_PASSWORD}
    expose:
      - ${SVIT_DB_PORT}
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        env: "dev"
    image: svit-image
    container_name: svit-service
    depends_on:
      - db
    restart: unless-stopped
    environment:
      SVIT_DB_USER: ${SVIT_DB_USER}
      SVIT_DB_NAME: ${SVIT_DB_NAME}
      SVIT_DB_PASSWORD: ${SVIT_DB_PASSWORD}
      SVIT_DB_PORT: ${SVIT_DB_PORT}
      SVIT_DB_HOST: "db"
    ports:
      - "8080:80"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
