#if !canImport(ObjectiveC)
import XCTest

extension HealthCheckTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HealthCheckTests = [
        ("testStatusUp", testStatusUp),
    ]
}

extension RelationCountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RelationCountTests = [
        ("testRelationsCountReturnsNotFound", testRelationsCountReturnsNotFound),
        ("testRelationsCountReturnsObject", testRelationsCountReturnsObject),
    ]
}

extension RelationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RelationTests = [
        ("testAddRelationIncrementsCount", testAddRelationIncrementsCount),
        ("testCreateRelation", testCreateRelation),
        ("testDeleteRelation", testDeleteRelation),
        ("testDeleteRelationDecrementsCount", testDeleteRelationDecrementsCount),
        ("testGetRelationsFromVertexToVertex", testGetRelationsFromVertexToVertex),
        ("testGetRelationsFromVertexWithType", testGetRelationsFromVertexWithType),
        ("testGetRelationsFromVertexWithTypeToVertexNotAllowed", testGetRelationsFromVertexWithTypeToVertexNotAllowed),
        ("testRelationLifecycle", testRelationLifecycle),
        ("testRelationUpdateData", testRelationUpdateData),
    ]
}

extension VertexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VertexTests = [
        ("testAddAndDeleteVertex", testAddAndDeleteVertex),
        ("testCreateVertex", testCreateVertex),
        ("testDeleteVertexWithRelations", testDeleteVertexWithRelations),
        ("testVertexUpdate", testVertexUpdate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HealthCheckTests.__allTests__HealthCheckTests),
        testCase(RelationCountTests.__allTests__RelationCountTests),
        testCase(RelationTests.__allTests__RelationTests),
        testCase(VertexTests.__allTests__VertexTests),
    ]
}
#endif
